# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

mydatabase = mysql.connector.connect(
    host='localhost',
    user='root',
    password='bre123no456',
    database='empresa'
)
cursor = mydatabase.cursor()


class Ui_Cadastro(object):
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.resize(777, 577)
        Cadastro.setStyleSheet("background-color: rgb(144, 174, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(Cadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(200, 50, 431, 81))
        self.label_titulo.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.label_nome = QtWidgets.QLabel(self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(20, 150, 171, 41))
        self.label_nome.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nome.setObjectName("label_nome")
        self.label_endereco = QtWidgets.QLabel(self.centralwidget)
        self.label_endereco.setGeometry(QtCore.QRect(20, 200, 171, 41))
        self.label_endereco.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_endereco.setAlignment(QtCore.Qt.AlignCenter)
        self.label_endereco.setObjectName("label_endereco")
        self.label_nascimento = QtWidgets.QLabel(self.centralwidget)
        self.label_nascimento.setGeometry(QtCore.QRect(20, 250, 171, 41))
        self.label_nascimento.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_nascimento.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nascimento.setObjectName("label_nascimento")
        self.label_sexo = QtWidgets.QLabel(self.centralwidget)
        self.label_sexo.setGeometry(QtCore.QRect(20, 300, 171, 41))
        self.label_sexo.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_sexo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sexo.setObjectName("label_sexo")
        self.label_nacionalidade = QtWidgets.QLabel(self.centralwidget)
        self.label_nacionalidade.setGeometry(QtCore.QRect(20, 350, 171, 41))
        self.label_nacionalidade.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_nacionalidade.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nacionalidade.setObjectName("label_nacionalidade")
        self.label_cpf = QtWidgets.QLabel(self.centralwidget)
        self.label_cpf.setGeometry(QtCore.QRect(20, 400, 171, 41))
        self.label_cpf.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.label_cpf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cpf.setObjectName("label_cpf")
        self.botao_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_enviar.setGeometry(QtCore.QRect(310, 490, 191, 61))
        self.botao_enviar.setStyleSheet("background-color: rgb(190, 0, 0);")
        self.botao_enviar.setObjectName("botao_enviar")
        self.LineNome = QtWidgets.QLineEdit(self.centralwidget)
        self.LineNome.setGeometry(QtCore.QRect(200, 150, 551, 41))
        self.LineNome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.LineNome.setObjectName("LineNome")
        self.LineEndereco = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEndereco.setGeometry(QtCore.QRect(200, 200, 551, 41))
        self.LineEndereco.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.LineEndereco.setObjectName("LineEndereco")
        self.LineNacionalidade = QtWidgets.QLineEdit(self.centralwidget)
        self.LineNacionalidade.setGeometry(QtCore.QRect(200, 350, 551, 41))
        self.LineNacionalidade.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.LineNacionalidade.setObjectName("LineNacionalidade")
        self.LineCpf = QtWidgets.QLineEdit(self.centralwidget)
        self.LineCpf.setGeometry(QtCore.QRect(200, 400, 551, 41))
        self.LineCpf.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.LineCpf.setObjectName("LineCpf")
        self.dataNascimento = QtWidgets.QDateEdit(self.centralwidget)
        self.dataNascimento.setGeometry(QtCore.QRect(200, 250, 201, 41))
        self.dataNascimento.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.dataNascimento.setObjectName("dataNascimento")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(220, 310, 51, 21))
        self.radioButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(300, 310, 41, 21))
        self.radioButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.radioButton_2.setObjectName("radioButton_2")
        Cadastro.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Cadastro)
        self.statusbar.setObjectName("statusbar")
        Cadastro.setStatusBar(self.statusbar)

        self.retranslateUi(Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)
        
        self.botao_enviar.clicked.connect(self.cadastrar)

    def retranslateUi(self, Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Cadastro.setWindowTitle(_translate("Cadastro", "MainWindow"))
        self.label_titulo.setText(_translate("Cadastro", "Cadastro de Clientes"))
        self.label_nome.setText(_translate("Cadastro", "Nome:"))
        self.label_endereco.setText(_translate("Cadastro", "Endereço:"))
        self.label_nascimento.setText(_translate("Cadastro", "Data de Nascimento:"))
        self.label_sexo.setText(_translate("Cadastro", "Sexo:"))
        self.label_nacionalidade.setText(_translate("Cadastro", "Nacionalidade:"))
        self.label_cpf.setText(_translate("Cadastro", "CPF(Números):"))
        self.botao_enviar.setText(_translate("Cadastro", "Enviar"))
        self.radioButton.setText(_translate("Cadastro", "M"))
        self.radioButton_2.setText(_translate("Cadastro", "F"))
        
           
    def cadastrar(self):
        inserir = True
        nome = self.LineNome.text()
        if len(nome) < 3:
            self.label_titulo.setText("ERRO!")
            inserir = False
        endereco = self.LineEndereco.text()
        if len(endereco) < 5:
            self.label_titulo.setText("ERRO!")
            inserir = False
        nascimento = self.dataNascimento.date().toPyDate()
        if self.radioButton.isChecked():
            sexo = 'M'
        elif self.radioButton_2.isChecked():
            sexo = 'F'
        else:
            sexo = ''
            self.label_titulo.setText('ERRO!')
            inserir = False
        nacionalidade = self.LineNacionalidade.text()
        if len(nacionalidade) < 3:
            self.label_titulo.setText('ERRO!')
            inserir = False
        cpf = self.LineCpf.text()
        if cpf.isdigit() == False or len(cpf) != 11:
            self.label_titulo.setText('ERRO!')
            inserir = False
        if inserir:
            comando = "insert into clientes (nome, endereco, nascimento, sexo, nacionalidade, cpf) values (%s, %s, %s, %s, %s, %s);"
            dados = (nome, endereco, nascimento, sexo, nacionalidade, cpf)
            cursor.execute(comando, dados)
            mydatabase.commit()
            
            self.LineNome.setText('')
            self.LineEndereco.setText('')
            self.LineNacionalidade.setText('')
            self.LineCpf.setText('')
            self.label_titulo.setText('Dado do Cliente Cadastrado!')
            
            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastro = QtWidgets.QMainWindow()
    ui = Ui_Cadastro()
    ui.setupUi(Cadastro)
    Cadastro.show()
    sys.exit(app.exec_())
