# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forca.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 582)
        MainWindow.setStyleSheet("background-color: rgb(76, 255, 82);\n"
"font: 75 16pt \"Times New Roman\";\n"
"color: rgb(13, 3, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(170, 20, 261, 51))
        self.label_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo.setObjectName("label_titulo")
        self.lista_forca = QtWidgets.QListWidget(self.centralwidget)
        self.lista_forca.setGeometry(QtCore.QRect(45, 80, 511, 271))
        self.lista_forca.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(7, 19, 255);")
        self.lista_forca.setObjectName("lista_forca")
        self.label_palavra = QtWidgets.QLabel(self.centralwidget)
        self.label_palavra.setGeometry(QtCore.QRect(160, 390, 281, 31))
        self.label_palavra.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 20pt \"Times New Roman\";")
        self.label_palavra.setText("")
        self.label_palavra.setAlignment(QtCore.Qt.AlignCenter)
        self.label_palavra.setObjectName("label_palavra")
        self.label_comandos = QtWidgets.QLabel(self.centralwidget)
        self.label_comandos.setGeometry(QtCore.QRect(30, 450, 251, 31))
        self.label_comandos.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label_comandos.setObjectName("label_comandos")
        self.lineletras = QtWidgets.QLineEdit(self.centralwidget)
        self.lineletras.setGeometry(QtCore.QRect(290, 450, 261, 31))
        self.lineletras.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.lineletras.setObjectName("lineletras")
        self.botao_enviar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_enviar.setGeometry(QtCore.QRect(210, 500, 171, 61))
        self.botao_enviar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(5, 38, 255);")
        self.botao_enviar.setObjectName("botao_enviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.botao_enviar.clicked.connect(self.jogar_forca)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titulo.setText(_translate("MainWindow", "Jogo da Forca"))
        self.label_comandos.setText(_translate("MainWindow", "Palavra Secreta:"))
        self.botao_enviar.setText(_translate("MainWindow", "Enviar"))
        
    def jogar_forca(self):
        if self.botao_enviar.text() == 'Jogar Novamente':
            self.botao_enviar.setText('Enviar')
            self.label_comandos.setText('Palavra Secreta:')
            self.lista_forca.clear()
            self.lineletras.setText('')
            self.label_titulo.setText('Jogo da Forca')
            self.label_palavra.setText('')
        elif self.label_comandos.text() == 'Palavra Secreta:':
            self.palavra_secreta = (self.lineletras.text().lower().strip())
            self.label_comandos.setText('Digite uma Letra:')
            self.lineletras.setText('')
            self.digitadas = []
            self.acertos = []
            self.erros = 0
        else:
            self.tentativa = self.lineletras.text().lower().strip()
            if self.tentativa in self.digitadas:
                self.label_titulo.setText('Você já tentou esta letra!')
                self.lineletras.setText('')
            else:
                self.digitadas += self.tentativa
                if self.tentativa in self.palavra_secreta:
                    self.acertos += self.tentativa
                else:
                    self.erros += 1
                    self.label_titulo.setText('Você errou!')
                self.lineletras.setText('')
                self.senha = ''
                for letra in self.palavra_secreta:
                    self.senha += letra if letra in self.acertos else '*'
                self.label_palavra.setText(self.senha)
                if self.senha == self.palavra_secreta:
                    self.label_titulo.setText('Você ganhou!')
                    self.botao_enviar.setText('Jogar Novamente')
            self.lista_forca.clear()
            self.lista_forca.addItem('X     :     ')
            self.lista_forca.addItem('X     :     '.replace('=', ' '))
            self.lista_forca.addItem('X     O     ') if self.erros >= 1 else self.lista_forca.addItem('X')
            self.linha2 = ''
            if self.erros == 2:
                self.linha2 = "     |     "
            elif self.erros == 3:
                self.linha2 = '    \|     '
            elif self.erros >= 4:
                self.linha2 = "    \|/    "
            self.lista_forca.addItem('X%s' %self.linha2)
            self.linha3 = ""
            if self.erros == 5:
                self.linha3 += "    /      "
            elif self.erros >= 6:
                self.linha3 += '    / \    '
            self.lista_forca.addItem('X%s'%self.linha3)
            self.lista_forca.addItem('X\n===================')
            if self.erros == 6:
                self.label_titulo.setText('Enforcado!')
                self.botao_enviar.setText('Jogar Novamente')
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
