# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Jokenpo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random


class Ui_Jokenpo(object):
    def setupUi(self, Jokenpo):
        Jokenpo.setObjectName("Jokenpo")
        Jokenpo.resize(584, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Jokenpo.setFont(font)
        Jokenpo.setStyleSheet("background-color: rgb(199, 249, 255);\n"
"font: 24pt \"Times New Roman\";")
        self.centralwidget = QtWidgets.QWidget(Jokenpo)
        self.centralwidget.setObjectName("centralwidget")
        self.Label_titulo = QtWidgets.QLabel(self.centralwidget)
        self.Label_titulo.setGeometry(QtCore.QRect(120, 30, 331, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_titulo.setFont(font)
        self.Label_titulo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(85, 42, 255);")
        self.Label_titulo.setObjectName("Label_titulo")
        self.ButtonPedra = QtWidgets.QRadioButton(self.centralwidget)
        self.ButtonPedra.setGeometry(QtCore.QRect(60, 150, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ButtonPedra.setFont(font)
        self.ButtonPedra.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(85, 42, 255);")
        self.ButtonPedra.setObjectName("ButtonPedra")
        self.ButtonPapel = QtWidgets.QRadioButton(self.centralwidget)
        self.ButtonPapel.setGeometry(QtCore.QRect(250, 150, 101, 51))
        self.ButtonPapel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(85, 42, 255);")
        self.ButtonPapel.setObjectName("ButtonPapel")
        self.ButtonTesoura = QtWidgets.QRadioButton(self.centralwidget)
        self.ButtonTesoura.setGeometry(QtCore.QRect(400, 150, 131, 51))
        self.ButtonTesoura.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid rgb(0, 0, 0);\n"
"color: rgb(85, 42, 255);")
        self.ButtonTesoura.setObjectName("ButtonTesoura")
        self.imagem_papel = QtWidgets.QLabel(self.centralwidget)
        self.imagem_papel.setGeometry(QtCore.QRect(250, 220, 111, 121))
        self.imagem_papel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagem_papel.setText("")
        self.imagem_papel.setObjectName("imagem_papel")
        self.imagem_tesoura = QtWidgets.QLabel(self.centralwidget)
        self.imagem_tesoura.setGeometry(QtCore.QRect(410, 220, 121, 121))
        self.imagem_tesoura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagem_tesoura.setText("")
        self.imagem_tesoura.setObjectName("imagem_tesoura")
        self.imagem_pedra = QtWidgets.QLabel(self.centralwidget)
        self.imagem_pedra.setGeometry(QtCore.QRect(60, 220, 121, 121))
        self.imagem_pedra.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imagem_pedra.setText("")
        self.imagem_pedra.setObjectName("imagem_pedra")
        self.BotaoJogar = QtWidgets.QPushButton(self.centralwidget)
        self.BotaoJogar.setGeometry(QtCore.QRect(220, 370, 151, 51))
        self.BotaoJogar.setStyleSheet("background-color: rgb(124, 37, 255);\n"
"color: rgb(255, 255, 255);")
        self.BotaoJogar.setObjectName("BotaoJogar")
        self.label_computador = QtWidgets.QLabel(self.centralwidget)
        self.label_computador.setGeometry(QtCore.QRect(60, 450, 481, 41))
        self.label_computador.setObjectName("label_computador")
        self.label_resultado = QtWidgets.QLabel(self.centralwidget)
        self.label_resultado.setGeometry(QtCore.QRect(60, 510, 481, 41))
        self.label_resultado.setText("")
        self.label_resultado.setObjectName("label_resultado")
        Jokenpo.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Jokenpo)
        self.statusbar.setObjectName("statusbar")
        Jokenpo.setStatusBar(self.statusbar)

        self.retranslateUi(Jokenpo)
        QtCore.QMetaObject.connectSlotsByName(Jokenpo)
        
        self.imagem_pedra.setPixmap(QtGui.QPixmap('pedra.png'))
        self.imagem_papel.setPixmap(QtGui.QPixmap('papel.png'))
        self.imagem_tesoura.setPixmap(QtGui.QPixmap('tesoura.png'))
        self.BotaoJogar.clicked.connect(self.funcao_principal)

    def retranslateUi(self, Jokenpo):
        _translate = QtCore.QCoreApplication.translate
        Jokenpo.setWindowTitle(_translate("Jokenpo", "MainWindow"))
        self.Label_titulo.setText(_translate("Jokenpo", "Pedra, Papel ou Tesoura?"))
        self.ButtonPedra.setText(_translate("Jokenpo", "Pedra"))
        self.ButtonPapel.setText(_translate("Jokenpo", "Papel"))
        self.ButtonTesoura.setText(_translate("Jokenpo", "Tesoura"))
        self.BotaoJogar.setText(_translate("Jokenpo", "JOGAR"))
        self.label_computador.setText(_translate("Jokenpo", "O computador escolheu:"))
        
    def funcao_principal(self):
        if self.ButtonPedra.isChecked():
            escolha = 'Pedra'
        elif self.ButtonPapel.isChecked():
            escolha = 'Papel'
        elif self.ButtonTesoura.isChecked():
            escolha = 'Tesoura'
        else:
            escolha = ''
        
        if escolha == '':
            self.label_resultado.setText('Escolha um valor!!!')
        else:
            Valores = ["Pedra", "Papel", "Tesoura"]
            computador = random.choice(Valores)
            self.label_computador.setText("O computador escolheu: "+computador)
            if computador == escolha:
                resultado = 'EMPATE'
            elif computador == 'Pedra':
                if escolha == 'Papel':
                    resultado = 'Você Ganhou'
                elif escolha == 'Tesoura':
                    resultado = 'Você Perdeu'
            elif computador == 'Papel':
                if escolha == 'Pedra':
                    resultado = 'Você Perdeu'
                elif escolha == 'Tesoura':
                    resultado = 'Você Ganhou'
            elif computador == 'Tesoura':
                if escolha == 'Pedra':
                    resultado = 'Você Ganhou'
                elif escolha == 'Papel':
                    resultado = 'Você Perdeu'
            self.label_resultado.setText(resultado)
                
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Jokenpo = QtWidgets.QMainWindow()
    ui = Ui_Jokenpo()
    ui.setupUi(Jokenpo)
    Jokenpo.show()
    sys.exit(app.exec_())
